/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai6_04;

import java.net.*;
import java.io.*;

/**
 *
 * @author Admin
 */
public class frmChat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmChat.class.getName());
    private MulticastSocket multicastSocket;
    private InetAddress group;
    private Thread receiveThread;
    private boolean running = false;
    private boolean connected = false;

    /**
     * Creates new form frmChat
     */
    public frmChat() {
        initComponents();
        setLocationRelativeTo(null);
        btnSend.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnoiDung = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình chat dùng Multicast");

        jLabel1.setText("Nhập địa chỉ Multicast");

        txtHost.setText("239.0.0.36");

        jLabel2.setText("Port");

        txtPort.setText("1234");

        jLabel3.setText("Nick");

        txtNick.setText("User");

        btnConnect.setText("Kết nối");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        txtNoiDung.setEditable(false);
        txtNoiDung.setColumns(20);
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        txtnoiDung.setColumns(20);
        txtnoiDung.setRows(5);
        jScrollPane2.setViewportView(txtnoiDung);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if (!connected) {
            // Kết nối
            try {
                String host = txtHost.getText().trim();
                int port = Integer.parseInt(txtPort.getText().trim());
                
                // Tạo multicast socket
                multicastSocket = new MulticastSocket(port);
                
                // Join multicast group
                group = InetAddress.getByName(host);
                multicastSocket.joinGroup(group);
                
                connected = true;
                running = true;
                
                // Bắt đầu nhận tin nhắn
                startReceiving();
                
                // Cập nhật UI
                btnConnect.setText("Ngắt kết nối");
                btnSend.setEnabled(true);
                txtHost.setEnabled(false);
                txtPort.setEnabled(false);
                
                txtNoiDung.append("Đã kết nối vào nhóm: " + host + ":" + port + "\n");
                
            } catch (NumberFormatException e) {
                txtNoiDung.append("Lỗi: Port không hợp lệ!\n");
            } catch (Exception e) {
                txtNoiDung.append("Lỗi kết nối: " + e.getMessage() + "\n");
                e.printStackTrace();
            }
        } else {
            // Ngắt kết nối
            disconnect();
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String message = txtnoiDung.getText().trim();
        String nick = txtNick.getText().trim();
        
        if (message.isEmpty()) {
            return;
        }
        
        if (!connected) {
            txtNoiDung.append("Chưa kết nối vào nhóm!\n");
            return;
        }
        
        try {
            // Tạo thông điệp
            String fullMessage = nick + ": " + message;
            byte[] buffer = fullMessage.getBytes();
            
            // Gửi packet đến multicast group
            DatagramPacket packet = new DatagramPacket(
                buffer, 
                buffer.length, 
                group, 
                Integer.parseInt(txtPort.getText().trim())
            );
            
            multicastSocket.send(packet);
            
            // Xóa nội dung đã gửi
            txtnoiDung.setText("");
            
        } catch (Exception e) {
            txtNoiDung.append("Lỗi khi gửi: " + e.getMessage() + "\n");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        disconnect();
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void startReceiving() {
        receiveThread = new Thread(() -> {
            byte[] buffer = new byte[1024];
            
            while (running) {
                try {
                    DatagramPacket packet = new DatagramPacket(buffer, buffer.length);
                    multicastSocket.receive(packet);
                    
                    String message = new String(packet.getData(), 0, packet.getLength());
                    
                    // Cập nhật UI từ thread
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        txtNoiDung.append(message + "\n");
                    });
                    
                } catch (SocketException e) {
                    if (running) {
                        System.err.println("Socket đã đóng");
                    }
                    break;
                } catch (Exception e) {
                    if (running) {
                        e.printStackTrace();
                    }
                    break;
                }
            }
        });
        receiveThread.start();
    }
    
    private void disconnect() {
        if (!connected) {
            return;
        }
        
        running = false;
        connected = false;
        
        try {
            if (multicastSocket != null) {
                // Leave multicast group
                if (group != null) {
                    multicastSocket.leaveGroup(group);
                }
                multicastSocket.close();
            }
            
            if (receiveThread != null) {
                receiveThread.join(1000);
            }
            
            // Cập nhật UI
            btnConnect.setText("Kết nối");
            btnSend.setEnabled(false);
            txtHost.setEnabled(true);
            txtPort.setEnabled(true);
            
            txtNoiDung.append("Đã ngắt kết nối.\n");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmChat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextArea txtnoiDung;
    // End of variables declaration//GEN-END:variables
}
